// LINEAGE Mock Data
// This data represents the shape of API responses from the FastAPI backend.
// Replace with real API calls when backend is ready.

export const MOCK_PROJECTS = [
  {
    id: 1,
    title: 'Low-cost Detection of Diabetic Retinopathy from Fundus Images on Edge Devices',
    public_summary: 'Develop an affordable AI-powered system to detect diabetic retinopathy from retinal fundus images, optimized for deployment on low-cost edge devices in rural healthcare settings. The project aims to make early screening accessible in areas with limited ophthalmologist availability.',
    confidential_brief: null, // Only available after authorization
    sponsor: { id: 3, name: 'Vikram Patel', organization: 'HealthTech India Foundation' },
    budget: 100000,
    currency: '₹',
    category: 'Medical AI',
    domain: 'Healthcare / Computer Vision',
    status: 'active',
    skills_required: ['Python', 'TensorFlow', 'Computer Vision', 'Medical Imaging', 'Edge Computing', 'Model Optimization'],
    created_at: '2026-09-15T10:00:00Z',
    updated_at: '2026-10-01T14:30:00Z',
    team_size: 5,
    milestones_total: 3,
    milestones_completed: 1,
    match_score: 92,
    match_reasons: [
      'Your Python and Computer Vision skills match the project requirements',
      'Your TensorFlow experience is directly relevant',
      'Your availability matches the project timeline',
    ],
  },
  {
    id: 2,
    title: 'Natural Language Processing for Regional Language Legal Documents',
    public_summary: 'Build an NLP pipeline to process, classify, and summarize legal documents written in regional Indian languages. This system will help rural legal aid organizations quickly understand and categorize case documents.',
    confidential_brief: null,
    sponsor: { id: 5, name: 'Ananya Desai', organization: 'LegalAid Foundation' },
    budget: 75000,
    currency: '₹',
    category: 'NLP',
    domain: 'Legal Tech / NLP',
    status: 'open',
    skills_required: ['Python', 'NLP', 'Transformers', 'Multilingual Models', 'Data Processing'],
    created_at: '2026-09-20T08:00:00Z',
    updated_at: '2026-09-28T11:00:00Z',
    team_size: 4,
    milestones_total: 4,
    milestones_completed: 0,
    match_score: 78,
    match_reasons: [
      'Your Python skills match the project requirements',
      'Some NLP experience detected in your profile',
    ],
  },
  {
    id: 3,
    title: 'Predictive Maintenance System for Solar Panel Arrays',
    public_summary: 'Design a machine learning system to predict maintenance needs for solar panel installations using sensor data and weather patterns. The system should identify potential failures before they occur to minimize downtime.',
    confidential_brief: null,
    sponsor: { id: 6, name: 'Rohan Mehta', organization: 'SolarGrid Technologies' },
    budget: 120000,
    currency: '₹',
    category: 'IoT / ML',
    domain: 'Clean Energy / IoT',
    status: 'open',
    skills_required: ['Python', 'Time Series Analysis', 'IoT', 'Sensor Data', 'Random Forest', 'Data Engineering'],
    created_at: '2026-10-01T09:00:00Z',
    updated_at: '2026-10-03T16:00:00Z',
    team_size: 3,
    milestones_total: 0,
    milestones_completed: 0,
    match_score: 65,
    match_reasons: [
      'Your Python skills are relevant',
    ],
  },
];

export const MOCK_MILESTONES = [
  {
    id: 1,
    project_id: 1,
    title: 'Dataset Preparation and Preprocessing',
    description: 'Collect, clean, and preprocess retinal fundus image datasets. Implement data augmentation pipeline and establish quality metrics for training data.',
    skills_required: ['Python', 'Data Processing', 'Computer Vision'],
    acceptance_criteria: [
      'Minimum 10,000 labeled fundus images collected',
      'Data augmentation pipeline producing 5x original dataset',
      'Quality metrics documented and threshold established',
      'Train/validation/test split with no data leakage',
    ],
    reward_amount: 25000,
    status: 'completed',
    ai_generated: true,
    order: 1,
  },
  {
    id: 2,
    project_id: 1,
    title: 'Model Development and Training',
    description: 'Design and train a lightweight CNN for diabetic retinopathy classification. Target accuracy >90% with model size <50MB for edge deployment.',
    skills_required: ['TensorFlow', 'Deep Learning', 'Model Optimization'],
    acceptance_criteria: [
      'Classification accuracy >90% on test set',
      'Model size under 50MB',
      'Training pipeline reproducible',
      'Performance benchmarks documented',
    ],
    reward_amount: 40000,
    status: 'in_progress',
    ai_generated: true,
    order: 2,
  },
  {
    id: 3,
    project_id: 1,
    title: 'Edge Deployment and Optimization',
    description: 'Optimize the trained model for edge devices using quantization and pruning. Deploy on target hardware and validate inference performance.',
    skills_required: ['Edge Computing', 'Model Optimization', 'TensorFlow Lite'],
    acceptance_criteria: [
      'Model runs on Raspberry Pi 4 or equivalent',
      'Inference time <2 seconds per image',
      'Accuracy degradation <2% from full model',
      'Deployment guide and documentation complete',
    ],
    reward_amount: 35000,
    status: 'pending',
    ai_generated: true,
    order: 3,
  },
];

export const MOCK_CHARTER = {
  id: 1,
  project_id: 1,
  version: 1,
  status: 'active',
  scope: 'Develop and deploy an edge-optimized deep learning model for diabetic retinopathy detection from fundus images. The system must achieve >90% accuracy while running on low-cost hardware.',
  roles: [
    { role: 'Sponsor', responsibilities: 'Provide funding, domain requirements, final acceptance' },
    { role: 'Expert', responsibilities: 'Technical guidance, code review, research methodology oversight' },
    { role: 'Student', responsibilities: 'Implementation, experimentation, documentation' },
  ],
  reward_terms: 'Rewards are distributed based on accepted contributions to final artifacts. Impact scores determine individual allocation from milestone budgets.',
  acceptance_criteria: 'All milestone acceptance criteria must be met. Expert review and sponsor sign-off required.',
  ip_terms: 'All contributions are open-source under MIT License. Sponsor retains right to commercial deployment.',
  created_at: '2026-09-16T10:00:00Z',
  updated_at: '2026-09-16T10:00:00Z',
  accepted_by: [
    { user_id: 2, name: 'Dr. Priya Menon', role: 'expert', accepted_at: '2026-09-17T08:00:00Z' },
    { user_id: 1, name: 'Arjun Sharma', role: 'student', accepted_at: '2026-09-17T09:30:00Z' },
  ],
};

export const MOCK_CONTRIBUTIONS = [
  {
    id: 'C-1001',
    contributor: { id: 1, name: 'Arjun Sharma', role: 'student' },
    artifact: 'preprocessing.py',
    milestone: { id: 1, title: 'Dataset Preparation and Preprocessing' },
    origin: 'human',
    ai_assisted: false,
    hash: 'sha256:a1b2c3d4e5f6789012345678abcdef0123456789abcdef0123456789abcdef01',
    status: 'accepted',
    created_at: '2026-09-25T14:30:00Z',
    similarity_score: null,
    impact_score: 8.5,
  },
  {
    id: 'C-1002',
    contributor: { id: 1, name: 'Arjun Sharma', role: 'student' },
    artifact: 'augmentation_pipeline.py',
    milestone: { id: 1, title: 'Dataset Preparation and Preprocessing' },
    origin: 'ai_assisted',
    ai_assisted: true,
    hash: 'sha256:b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef012',
    status: 'accepted',
    created_at: '2026-09-27T10:15:00Z',
    similarity_score: 23,
    impact_score: 7.0,
  },
  {
    id: 'C-1003',
    contributor: { id: 1, name: 'Arjun Sharma', role: 'student' },
    artifact: 'model_v1.py',
    milestone: { id: 2, title: 'Model Development and Training' },
    origin: 'ai_assisted',
    ai_assisted: true,
    hash: 'sha256:c3d4e5f678901234567890abcdef0123456789abcdef0123456789abcdef0123',
    status: 'flagged',
    created_at: '2026-10-02T16:45:00Z',
    similarity_score: 87,
    impact_score: null,
  },
  {
    id: 'C-1004',
    contributor: { id: 2, name: 'Dr. Priya Menon', role: 'expert' },
    artifact: 'research_methodology.md',
    milestone: { id: 2, title: 'Model Development and Training' },
    origin: 'human',
    ai_assisted: false,
    hash: 'sha256:d4e5f6789012345678901abcdef0123456789abcdef0123456789abcdef01234',
    status: 'accepted',
    created_at: '2026-10-01T11:00:00Z',
    similarity_score: 12,
    impact_score: 9.0,
  },
];

export const MOCK_LEDGER = [
  {
    entry_number: 101,
    contribution_id: 'C-1001',
    admin: { id: 4, name: 'Neha Gupta' },
    previous_hash: '0000000000000000000000000000000000000000000000000000000000000000',
    current_hash: '91af3e2b7c8d4f5a6b0e1234567890abcdef0123456789abcdef0123456789ab',
    timestamp: '2026-09-25T15:00:00Z',
    status: 'valid',
    action: 'Contribution C-1001 accepted and recorded',
  },
  {
    entry_number: 102,
    contribution_id: 'C-1002',
    admin: { id: 4, name: 'Neha Gupta' },
    previous_hash: '91af3e2b7c8d4f5a6b0e1234567890abcdef0123456789abcdef0123456789ab',
    current_hash: '8a23f1c4d5e6789012345678abcdef0123456789abcdef0123456789abcdef01',
    timestamp: '2026-09-27T11:00:00Z',
    status: 'valid',
    action: 'Contribution C-1002 accepted and recorded',
  },
  {
    entry_number: 103,
    contribution_id: 'C-1004',
    admin: { id: 4, name: 'Neha Gupta' },
    previous_hash: '8a23f1c4d5e6789012345678abcdef0123456789abcdef0123456789abcdef01',
    current_hash: 'f5a6b7c8d9e0123456789012abcdef0123456789abcdef0123456789abcdef01',
    timestamp: '2026-10-01T12:00:00Z',
    status: 'valid',
    action: 'Contribution C-1004 accepted and recorded',
  },
];

export const MOCK_MATCHING = [
  {
    user: { id: 1, name: 'Arjun Sharma', role: 'student', avatar_color: '#00b4d8' },
    skills: ['Python', 'Machine Learning', 'Computer Vision', 'TensorFlow'],
    availability: 'part-time',
    match_score: 94,
    reasons: [
      'Python proficiency matches requirement',
      'Machine Learning experience directly relevant',
      'Computer Vision skills match project domain',
      'Availability aligns with milestone timeline',
    ],
    conflict_of_interest: false,
  },
  {
    user: { id: 7, name: 'Kavitha Rajan', role: 'student', avatar_color: '#e76f51' },
    skills: ['Python', 'TensorFlow', 'Data Science', 'Statistics'],
    availability: 'full-time',
    match_score: 86,
    reasons: [
      'Strong Python and TensorFlow skills',
      'Data Science background useful for preprocessing',
      'Full-time availability',
    ],
    conflict_of_interest: false,
  },
  {
    user: { id: 8, name: 'Rahul Verma', role: 'student', avatar_color: '#2a9d8f' },
    skills: ['Python', 'Edge Computing', 'Raspberry Pi', 'IoT'],
    availability: 'part-time',
    match_score: 79,
    reasons: [
      'Edge computing expertise critical for Milestone 3',
      'Raspberry Pi deployment experience',
    ],
    conflict_of_interest: false,
  },
  {
    user: { id: 2, name: 'Dr. Priya Menon', role: 'expert', avatar_color: '#0f3460' },
    skills: ['Deep Learning', 'Medical Imaging', 'Research Methodology', 'Edge Computing'],
    availability: 'advisory',
    match_score: 97,
    reasons: [
      'Domain expert in Medical Imaging',
      'Deep Learning research background',
      'Published papers in retinal image analysis',
      'Edge computing deployment experience',
    ],
    conflict_of_interest: false,
  },
];

export const MOCK_REVIEWS = [
  {
    id: 1,
    contribution_id: 'C-1003',
    reviewer: { id: 2, name: 'Dr. Priya Menon', role: 'expert' },
    similarity_score: 87,
    impact_score: null,
    integrity_status: 'flagged',
    decision: 'needs_review',
    comments: 'High similarity score detected. The model architecture closely resembles a published implementation. Need to verify if the contributor properly attributed the source and made meaningful modifications.',
    created_at: '2026-10-03T09:00:00Z',
  },
];

export const MOCK_ESCROW = {
  project_id: 1,
  total_budget: 100000,
  funded_amount: 100000,
  released_amount: 25000,
  remaining: 75000,
  currency: '₹',
  status: 'funded',
  milestones: [
    { milestone_id: 1, amount: 25000, status: 'released' },
    { milestone_id: 2, amount: 40000, status: 'funded' },
    { milestone_id: 3, amount: 35000, status: 'funded' },
  ],
};

export const MOCK_REWARDS = [
  {
    id: 1,
    recipient: { id: 1, name: 'Arjun Sharma', role: 'student' },
    contribution_id: 'C-1001',
    milestone: { id: 1, title: 'Dataset Preparation and Preprocessing' },
    amount: 10000,
    currency: '₹',
    impact_score: 8.5,
    reason: 'Accepted contribution from Milestone 1 - Dataset preprocessing pipeline',
    status: 'released',
    paid_at: '2026-09-28T10:00:00Z',
  },
  {
    id: 2,
    recipient: { id: 1, name: 'Arjun Sharma', role: 'student' },
    contribution_id: 'C-1002',
    milestone: { id: 1, title: 'Dataset Preparation and Preprocessing' },
    amount: 8500,
    currency: '₹',
    impact_score: 7.0,
    reason: 'Accepted contribution from Milestone 1 - Data augmentation pipeline',
    status: 'released',
    paid_at: '2026-09-29T14:00:00Z',
  },
  {
    id: 3,
    recipient: { id: 2, name: 'Dr. Priya Menon', role: 'expert' },
    contribution_id: 'C-1004',
    milestone: { id: 2, title: 'Model Development and Training' },
    amount: 6500,
    currency: '₹',
    impact_score: 9.0,
    reason: 'Accepted contribution from Milestone 2 - Research methodology document',
    status: 'released',
    paid_at: '2026-10-02T10:00:00Z',
  },
];

export const MOCK_AI_ACTIONS = [
  {
    id: 1,
    agent: 'LINEAGE Research Assistant',
    owner: { id: 1, name: 'Arjun Sharma' },
    project_id: 1,
    action: 'Generated experiment suggestions for model architecture',
    context_snapshot: 'v17',
    files_shared: ['model.py', 'schema.py', 'tests/'],
    redacted_items: ['API key', 'Database password'],
    ai_model: 'Gemini',
    status: 'reviewed',
    created_at: '2026-10-01T14:00:00Z',
  },
  {
    id: 2,
    agent: 'LINEAGE Research Assistant',
    owner: { id: 1, name: 'Arjun Sharma' },
    project_id: 1,
    action: 'Reviewed preprocessing code for potential improvements',
    context_snapshot: 'v12',
    files_shared: ['preprocessing.py', 'data_loader.py'],
    redacted_items: [],
    ai_model: 'Nemotron',
    status: 'reviewed',
    created_at: '2026-09-28T11:00:00Z',
  },
];

export const MOCK_DISPUTES = [
  {
    id: 1,
    reason: 'Contribution C-1003 was flagged but the similarity is due to using a standard ResNet architecture which is expected.',
    contribution_id: 'C-1003',
    raised_by: { id: 1, name: 'Arjun Sharma', role: 'student' },
    status: 'open',
    resolution: null,
    created_at: '2026-10-04T08:00:00Z',
  },
];

export const MOCK_TRUST_OVERVIEW = {
  project_id: 1,
  charter: { status: 'accepted', label: 'Charter accepted by all team members' },
  team: { status: 'verified', label: 'All team members verified' },
  ai_activity: { status: 'logged', label: 'All AI actions logged and reviewed' },
  contributions: { status: 'recorded', label: '4 contributions recorded, 3 accepted' },
  integrity: { status: 'review_required', label: '1 submission requires human review' },
  ledger: { status: 'valid', label: 'Ledger chain intact — 3 entries verified' },
  escrow: { status: 'funded', label: '₹1,00,000 funded, ₹25,000 released' },
};

export const MOCK_NOTIFICATIONS = [
  {
    id: 1,
    type: 'contribution_flagged',
    title: 'Contribution Flagged',
    message: 'Your contribution C-1003 (model_v1.py) has been flagged for similarity review.',
    read: false,
    created_at: '2026-10-03T09:15:00Z',
  },
  {
    id: 2,
    type: 'reward_released',
    title: 'Reward Released',
    message: '₹10,000 has been released for your contribution to Milestone 1.',
    read: true,
    created_at: '2026-09-28T10:05:00Z',
  },
  {
    id: 3,
    type: 'milestone_completed',
    title: 'Milestone Completed',
    message: 'Milestone 1: Dataset Preparation has been marked as completed.',
    read: true,
    created_at: '2026-09-28T09:00:00Z',
  },
];

// Dashboard stats by role
export const MOCK_DASHBOARD_STATS = {
  student: {
    active_projects: 1,
    contributions: 3,
    accepted_contributions: 2,
    total_rewards: 18500,
    currency: '₹',
    pending_reviews: 1,
  },
  expert: {
    active_collaborations: 1,
    reviews_completed: 3,
    pending_reviews: 1,
    contributions: 1,
    total_rewards: 6500,
    currency: '₹',
  },
  sponsor: {
    total_projects: 1,
    active_projects: 1,
    total_budget: 100000,
    released_funds: 25000,
    currency: '₹',
    pending_applications: 2,
    milestones_completed: 1,
  },
  admin: {
    total_users: 12,
    active_projects: 3,
    pending_reviews: 2,
    flagged_submissions: 1,
    ledger_entries: 3,
    ledger_status: 'valid',
    open_disputes: 1,
    escrow_total: 295000,
    currency: '₹',
  },
};
